### ISSUE TITLE
Pocket library outdated

### ISSUE THREAD

**Issue by vincentschen** [anoved/ReadingListReader#13]

**Comment by anoved** [comment]
Thanks for the heads up. I can no longer maintain this project as I no longer have an OS X machine. However I will gladly accept patches or endorse a current fork!

**Comment by vincentschen** [comment]
Sounds good! Created a pull request with basic functionality using [a new library](https://github.com/tapanpandita/pocket).

**Comment by anoved** [comment]
Thanks for the patch. #14
